import Registration from "@/components/registration";
import { Metadata } from "next";
import "@/styles/root/index.css";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

interface RootLayoutProps {
  children: React.ReactNode;
  onbording: React.ReactNode;
  pages: React.ReactNode;
}

export default function RootLayout({ onbording, pages }: RootLayoutProps) {
  return (
    <html lang="en">
      <body>
        <Registration>
          {onbording}
          {pages}
        </Registration>
      </body>
    </html>
  );
}
