import Registration from "@/components/registration";
import { Metadata } from "next";
import "@/styles/root/index.css";
import ReduxProvider from "@/components/reduxProvider";

export const metadata: Metadata = {
  title: "POST.",
  description: "Generated by Mudammad Amin Sherzod Aliy",
};

interface RootLayoutProps {
  children: React.ReactNode;
  onbording: React.ReactNode;
  pages: React.ReactNode;
}

export default function RootLayout({ onbording, pages }: RootLayoutProps) {
  return (
    <html lang="en">
      <body>
        <ReduxProvider>
          <Registration>
            {onbording}
            {pages}
          </Registration>
        </ReduxProvider>
      </body>
    </html>
  );
}
